# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    # Scheduled 10:30 AM Sunday UTC weekly
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:30"
    open-pull-requests-limit: 10
    labels:
      - "maven dependencies"
  # Enable version updates for Java and Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    # Scheduled 10:30 AM Sunday UTC weekly
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:30"
    open-pull-requests-limit: 10
    labels:
      - "gradle dependencies"
  # Temporarily disable the version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    # Scheduled 10:30 AM Sunday UTC weekly
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:30"
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0
    labels:
      - "docker dependencies"
