# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "mvn"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:30"
    open-pull-requests-limit: 10
    labels:
      - "mvn dependencies"
  # Enable version updates for Java
  - package-ecosystem: "java"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:30"
    open-pull-requests-limit: 10
    labels:
      - "java dependencies"
  # Temporarily disable the version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:30"
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0
    labels:
      - "docker dependencies"
